---
- name: Create file and mange permissions on all servers
  hosts: all
  tasks:
    - name: File creation
      file:
        name: /tmp/file1
        state: touch
        owner: sai
        group: Anusha
        mode: 750
...
