---
- name: Delete if the file is executable
  hosts: all
  tasks:
    - name: Capture file inof
      stat:
        name: /tmp/file1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Delete executable file
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true
...
