---
- name: Create an empty folder and download jenkins.war
  hosts: all
  tasks:
    - name: Create empty folder
      file:
        name: /tmp/myfolder
        state: directory
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.528.3/jenkins.war
        dest: /tmp/myfolder
...
