---
- name: Create a user on all servers
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: User creation
      user:
        name: Anusha
        password: intelliqit
        home: /tmp/Anusha
        uid: 7789
        comment: "a normal user"
        shell: /bin/bash


...
