---
- name: Implementing hsot scope variables
  hosts: 172.31.29.110
  tasks:
    - name: User creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
