---
- name: Implemnting loops
  hosts: all
  tasks:
    - name: Install s/w apps
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - tree
        - maven
        - openjdk-17-jdk
...
