---
- name: Check for f1 folder if it is not present create a file f1
  hosts: all
  tasks:
    - name: Check fo f1 fodler
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Print the output of the above module
      debug:
        var: a
    - name: Create f1 file if f1 folder is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
